#ifndef __RESGUID_H
#define __RESGUID_H

DEFINE_LG_GUID(IID_IResMan, 0x120);
DEFINE_LG_GUID(IID_IRes, 0x121);
DEFINE_LG_GUID(IID_IResType, 0x122);
DEFINE_LG_GUID(IID_IStoreFactory, 0x2F1);
DEFINE_LG_GUID(IID_IStoreHierarchy, 0x2F2);

DEFINE_LG_GUID(IID_IResMemOverride, 0x125);
DEFINE_LG_GUID(IID_IStore, 0x2F4);
DEFINE_LG_GUID(IID_IStoreStream, 0x2F5);

DEFINE_LG_GUID(IID_IResManHelper, 0x3B1);
DEFINE_LG_GUID(IID_IResStats, 0x3B2);
DEFINE_LG_GUID(IID_IResMem, 0x3B3);
DEFINE_LG_GUID(IID_IResControl, 0x3B4);
DEFINE_LG_GUID(IID_IStoreManager, 0x3B5);
DEFINE_LG_GUID(IID_ISearchPath, 0x3B6);

DEFINE_LG_GUID(IID_IResHack, 0x3F6);
DEFINE_LG_GUID(IID_IStringRes, 0x403);
DEFINE_LG_GUID(IID_IDataSource, 0x502);

#endif /* !__RESGUID_H */
