; $Header: x:/prj/tech/libsrc/g2/RCS/tmaps.inc 1.2 1997/05/16 09:48:08 KEVIN Exp $


G2S_TMAP_BM                     equ 0t
G2S_TMAP_P_DEST                 equ 4t
G2S_TMAP_P_SRC                  equ 8t
G2S_TMAP_DSRC_CARRY             equ 12t
G2S_TMAP_DSRC                   equ 16t
G2S_TMAP_DU_FRAC                equ 20t
G2S_TMAP_DV_FRAC                equ 24t
G2S_TMAP_MASK                   equ 36t
G2S_TMAP_DROW                   equ 40t
G2S_TMAP_I                      equ 42t
G2S_TMAP_LTAB                   equ 50t
G2S_TMAP_DIX                    equ 58t
G2S_TMAP_DUX                    equ 62t
G2S_TMAP_DVX                    equ 66t