#
# $Header: r:/t2repos/thief2/libsrc/gadget/makefile,v 1.10 1998/08/04 10:21:07 JAEMZ Exp $

MAKETOP = $(CWD)

PROJECT = cam

%include $(MRC)\env.rc

%include $(MRC)\init.rc

LIBTARGS=gadget

gadget_OBJS=gadget drawelem util2d gcompose uibutton gadblist gadtext \
        uitexted guistyle

gadget_HDRS=gadget.h drawelem.h util2d.h lgadover.h utilcomp.h \
        gcompose.h uibutton.h gadblist.h gadtext.h uitexted.h \
        guistyle.h gadbase.h gadbutt.h gadbox.h gadscale.h gadmenu.h gadint.h


%include  $(MRC)\make.rc

