//
// $Source: r:/prj/lib/src/timer/rcs/tmreg.inc $
// $Revision: 1.1 $
// $Author
// $Date: 1993/05/20 15:50:46 $
//
// Timer port/mode definitions.
//
// This file is part of the timer library.
//
// $Log: tmreg.inc $
// Revision 1.1  1993/05/20  15:50:46  kaboom
// Initial revision
// 
#define TMD_INT (8)
#define TMD_FREQ (1193180)
#define TMD_DEF_DENOM (0x10000)
#define TMP_MODE (0x43)
#define TMP_CHAN0 (0x40)
#define TMM_RATEGEN (0x34)
#define TMM_SQUARE (0x36)